import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata, Viewport } from "next";

import { Analytics } from "@vercel/analytics/next"
import SwRegister from "@/components/SwRegister";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // metadataBase resolves relative OG/Twitter image URLs (e.g. "/banner.png")
  // to absolute URLs, which crawlers require.
  metadataBase: new URL("https://konneqta.com"),
  title: "Konneqta",
  description: "Connect Smarter, Beyond The Internet",
  // The Web App Manifest is generated by app/manifest.ts (Next.js 16 file
  // convention). Next.js auto-injects <link rel="manifest"> here.
  manifest: "/manifest.webmanifest",
  // iOS "Add to Home Screen" — standalone launch, custom status bar.
  appleWebApp: {
    capable: true,
    title: "Konneqta",
    statusBarStyle: "black-translucent",
  },
  // Default rich-preview card for non-profile routes (home, login, etc.).
  // Profile pages override these via generateMetadata in app/[username]/page.tsx.
  openGraph: {
    title: "Konneqta",
    description: "Connect Smarter, Beyond The Internet",
    siteName: "Konneqta",
    type: "website",
    images: [
      {
        url: "/banner.png",
        width: 1200,
        height: 630,
        alt: "Konneqta",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Konneqta",
    description: "Connect Smarter, Beyond The Internet",
    images: ["/banner.png"],
  },
  icons: {
    icon: [
      { url: "/favicon-48x48.png", sizes: "48x48", type: "image/png" },
      {
        url: "/favicon.svg",
        type: "image/svg+xml",
      },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      // PWA installable icons (regular, non-maskable).
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      // High-res icon for iOS home screen + splash. Opaque black bg matches
      // the manifest theme so the launch screen looks intentional.
      { url: "/icons/apple-touch-180.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

// themeColor moved to Viewport in Next.js 14+ (Metadata no longer accepts it).
// This drives the Android PWA status-bar / address-bar tint.
export const viewport: Viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add('dark');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster position="top-right" richColors />
        <Analytics />
        {/* Registers /sw.js in production only (Serwist offline shell). */}
        <SwRegister />
      </body>
    </html>
  );
}
