import type { MetadataRoute } from "next";

/**
 * Web App Manifest — Next.js 16 file convention.
 *
 * Next.js auto-emits this at `/manifest.webmanifest` and injects the matching
 * `<link rel="manifest">` tag into <head>, so the app becomes installable
 * (Add to Home Screen / Install app) on Android, iOS (16.4+) and desktop.
 *
 * Stack note: this is independent of the Serwist service worker (app/sw.ts).
 *   - Manifest  → installability + icon + splash screen.
 *   - SW        → offline shell + caching.
 * Both are required for a full PWA; neither replaces the other.
 *
 * Icons live in /public/icons and are regenerated by
 * `node scripts/generate-pwa-icons.mjs`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Konneqta",
    short_name: "Konneqta",
    description: "Connect Smarter, Beyond The Internet",
    start_url: "/",
    scope: "/",
    // standalone = opens in its own window, no browser chrome.
    display: "standalone",
    // Allow iOS Safari to show the install banner / standalone launch.
    display_override: ["standalone", "minimal-ui"],
    orientation: "portrait",
    background_color: "#000000",
    theme_color: "#000000",
    categories: ["social", "business", "productivity"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        // Maskable: safe-zone padded so Android adaptive shapes don't crop
        // the wordmark. Generated at 64% of the 512 canvas.
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        // Some Android launchers still request a maskable at 192.
        src: "/icons/icon-maskable-512.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      {
        name: "My Profile",
        short_name: "Profile",
        description: "Open your Konneqta profile",
        url: "/post-login",
      },
    ],
  };
}